package PersonaApp;


/**
* PersonaApp/Persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 22 de abril de 2019 19H20' COT
*/

public interface Persona extends PersonaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Persona
